let wordlist = [
    "osfe",
    "osf",
    "OSFE",
    "OSF",
    "@OSFETABASCO",
    "OSFETABASCO",
    "Alejandro Álvarez",
    "Alejandro Álvarez González",
    "Fiscal Superior",
    "PRD",
    "PRI",
    "Morena",
    "MORENA",
    "PAN",
    "PT",
    "Partido Verde",
    "Movimiento Ciudadano",
    "Partido Encuentro Solidario",
    "PES",
    "FxM",
    "RSP",
    "PVEM",
    "Adán Augusto",
    "Adan Augusto",
    "AALH",
    "gobernador",
    "gobernadora",
    "estatal",
    "AMLO",
    "Andres Manuel",
    "Lopéz Obrador",
    "AMLO",
    "SOTOP",
    "IEPCT",
    "IEPC",
    "ITAIP",
    "TEPJF",
    "FGE",
    "SCT",
    "IPCET",
    "proteccion civil",
    "protección civil",
    "Protección Civil",
    "SESEA",
    "política",
    "diputado",
    "diputada",
    "alcalde",
    "edíl",
    "CFE",
    "ISSET",
    "INE",
    "plurinominales",
    "expresidente",
    "SESESP",
    "electoral",
    "servidores públicos",
    "servidor público",
    "diputaciones",
    "Evaristo",
    "TET",
    "Gaudiano",
    "Granier",
    "mdp",
    "millones de pesos",
    "ASF",
    "ASOFIS",
    "FGR",
    "SFP",
    "Secretaría de Salud",
    "Ayuntamiento",
    "Municipio",
    "congreso",
    "candidatura",
    "DIF",
    "diputación",
    "simpatizante",
    "aspirantes",
    "millones de pesos",
    "infringir",
    "proceso electoral",
    "municipios",
    "reelección",
    "denuncia",
    "políticos",
    "circunscripcion",
    "circunscripción",
    "recursos públicos",
    "mil pesos",
    "elecciones",
    "SSPC",
    "alcaldesa",
    "mil mdp",
    "subsidios",
    "subsidio",
    "juez",
    "jueza",
    "jueces",
    "Tribunal Federal",
    "SETAB",
    "Secretaría de Educación",
    "sindicato",
    "Fiscalía",
    "MoviTab",
    "impugnar",
    "amparo",
    "legislador",
    "Nuñez",
    "cabildo",
    "municipal",
    "Municipal",
    "senado",
    "senador",
    "senadores",
    "SEP",
    "tribunal",
    "PREPET",
    "SCJN",
    "SEDATU",
    "(SEDATU)",
    "(OSFE)",
    "(OSF)",
    "(PRD)",
    "(PRI)",
    "(MORENA)",
    "(PAN)",
    "(PT)",
    "(PES)",
    "(FxM)",
    "(RSP)",
    "(PVEM)",
    "(SOTOP)",
    "(IEPCT)",
    "(IEPC)",
    "(ITAIP)",
    "(TEPJF)",
    "(FGE)",
    "(SCT)",
    "(IPCET)",
    "(SESEA)",
    "(CFE)",
    "(ISSET)",
    "(INE)",
    "(SESESP)",
    "(TET)",
    "(ASF)",
    "(ASOFIS)",
    "(FGR)",
    "(SFP)",
    "(DIF)",
    "(SSPC)",
    "(SETAB)",
    "(SEP)",
    "(PREPET)",
    "(SCJN)",
    "distribuidor",
    "órganos autónomos",
    "INAI",
    "(INAI)",
    "cuidadania"
];