let wordlist = [
    [" osfe", 50],
    [" osf", 50],
    [" OSFE", 50],
    [" OSF", 50],
    ["(OSFE)", 50],
    ["(OSF)", 50],
    ["#OSFE", 50],
    ["Órgano Superior de Fiscalización del Estado", 50],
    ["Órgano Superior de Fiscalización", 50],
    ["@OSFETABASCO", 50],
    ["OSFETABASCO", 50],
    ["Alejandro Álvarez", 50],
    ["Alejandro Álvarez González", 50],
    ["Fiscal Superior", 50],
    ["SOTOP", 5],
    ["IEPCT", 5],
    ["IEPC", 5],
    ["ITAIP", 5],
    ["TEPJF", 5],
    ["FGE", 5],
    ["SCT", 5],
    ["SESEA", 5],
    ["CFE", 5],
    ["ISSET", 5],
    ["INE", 5],
    ["SESESP", 5],
    ["TET", 5],
    ["ASF", 5],
    ["ASOFIS", 5],
    ["FGR", 5],
    ["SFP", 5],
    ["DIF", 5],
    ["SSPC", 5],
    ["SETAB", 5],
    ["SEP", 5],
    ["PREPET", 5],
    ["SCJN", 5],
    ["SEDATU", 5],
    ["INAI", 5],
    ["Inai", 5],
    ["UJAT", 5],
    ["(UJAT)", 5],
    ["IFT", 5],
    ["FEDE", 5],
    ["(FEDE)", 5],
    ["(IFT)", 5],
    ["UT", 5],
    ["(UT)", 5],
    ["COBATAB", 5],
    ["(COBATAB)", 5],
    ["(SEDATU)", 5],
    ["(SOTOP)", 5],
    ["(IEPCT)", 5],
    ["(IEPC)", 5],
    ["(ITAIP)", 5],
    ["(TEPJF)", 5],
    ["(FGE)", 5],
    ["(SCT)", 5],
    ["(SESEA)", 5],
    ["(CFE)", 5],
    ["(ISSET)", 5],
    ["(INE)", 5],
    ["(SESESP)", 5],
    ["(TET)", 5],
    ["(ASF)", 5],
    ["(ASOFIS)", 5],
    ["(FGR)", 5],
    ["(SFP)", 5],
    ["(DIF)", 5],
    ["(SSPC)", 5],
    ["(SETAB)", 5],
    ["(SEP)", 5],
    ["(PREPET)", 5],
    ["(SCJN)", 5],
    ["(INAI)", 5],
    ["(Inai)", 5],
    ["Pemex", 5],
    ["PEMEX", 5],
    ["(PEMEX)", 5],
    ["PRI-PAN", 5],
    ["PRIAN", 5],
    ["UIF", 5],
    ["(UIF)", 5],
    ["Fiscalía General de la República", 5],
    ["Secretaría de Salud", 5],
    ["Secretaría de Educación", 5],
    ["órganos autónomos", 5],
    ["Tribunal Federal", 5],
    ["proteccion civil", 4],
    ["protección civil", 4],
    ["Protección Civil", 4],
    ["(IPCET)", 4],
    ["IPCET", 4],
    ["mil pesos", 4],    
    ["mdp", 4],    
    ["millones de pesos", 4],
    ["mil mdp", 4],
    ["subsidios", 4],
    ["subsidio", 4],
    ["recursos públicos", 4],
    ["política", 3],
    ["Adán Augusto", 3],
    ["Adan Augusto", 3],
    ["@Gobierno_Tab", 3],
    ["AALH", 3],
    ["gobernador", 3],
    ["gobernadora", 3],
    ["estatal", 3],
    ["AMLO", 3],
    ["(AMLO)", 3],
    ["Andres Manuel", 3],
    ["Andrés Manuel López Obrador", 3],
    ["López Obrador", 3],
    ["Obrador", 3],
    ["tabasqueño", 3],
    ["diputado", 3],
    ["diputada", 3],
    ["alcalde", 3],
    ["edíl", 3],
    ["plurinominales", 3],
    ["alcaldesa", 3],
    ["cabildo", 3],
    ["municipal", 3],
    ["Municipal", 3],
    ["Ayuntamiento", 3],
    ["Municipio", 3],
    ["congreso", 3],
    ["Congreso", 3],
    ["Congreso del Estado", 3],
    ["municipios", 3],
    ["secretario", 3],
    ["secretaria", 3],
    ["secretaría", 3],
    ["expresidente", 3],
    ["servidores públicos", 3],
    ["servidor público", 3],
    ["procedimiento de responsabilidad administrativa", 3],
    ["infringir", 3],
    ["sindicato", 3],
    ["PRD", 2],
    ["PRI", 2],
    ["Morena", 2],
    ["MORENA", 2],
    ["PAN", 2],
    ["PT", 2],    
    ["PES", 2],
    ["FxM", 2],
    ["RSP", 2],
    ["PVEM", 2],
    ["Partido Verde", 2],
    ["Movimiento Ciudadano", 2],
    ["Partido Encuentro Solidario", 2],
    ["(PRD)", 2],
    ["(PRI)", 2],
    ["(MORENA)", 2],
    ["(PAN)", 2],
    ["(PT)", 2],
    ["(PES)", 2],
    ["(FxM)", 2],
    ["(RSP)", 2],
    ["(PVEM)", 2],
    ["electoral", 2],
    ["candidatura", 2],
    ["diputaciones", 2],    
    ["diputación", 2],
    ["políticos", 2],
    ["simpatizante", 2],
    ["aspirantes", 2],
    ["reelección", 2],    
    ["proceso electoral", 2],
    ["elecciones", 2],
    ["circunscripcion", 2],
    ["circunscripción", 2],    
    ["legislador", 1],
    ["senado", 1],
    ["senador", 1],
    ["senadora", 1],
    ["senadoras", 1],
    ["senadores", 1],
    ["juez", 1],
    ["jueza", 1],
    ["jueces", 1],
    ["tribunal", 1],
    ["impugnar", 1],
    ["amparo", 1],
    ["Fiscalía", 1],
];